### PR TITLE
Upgrade to 1.22.3

### PR DESCRIPTION
**Pull request by misery**
* Upgrade pcsc-lite to 1.9.5, too.
* Use tarball instead of git - so we can check the hashsum
  of the release and notice if the source was changed.

### CODE REVIEW

**Comment by misery** [comment]
Ping? :-) Is it possible to get repository rights?

**Comment by e-user** [comment]
@misery uuuuh good question, I need to find out how to request this, I don't have admin permissions myself, but I'd be very happy to have you aboard!

**Comment by e-user** [comment]
Update, request created at https://github.com/flathub/flathub/issues/2839

**Comment by misery** [comment]
Thanks!

**Pull request merged**
